spring:
  datasource:
    url: ${GYPSY_BOARD_POSTGRES_URL:jdbc:postgresql://localhost:5435/gypsyboard}
    username: ${GYPSY_BOARD_POSTGRES_USER:admin}
    password: ${GYPSY_BOARD_POSTGRES_PASS:admin}
    driver-class-name: org.postgresql.Driver
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/
  web:
    resources:
      static-locations: classpath:/static
  cache:
    type: "none"
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.gypsy.board@gmail.com
    password: H@ck3r00
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true

server:
  port: 8000

application:
  token:
    lifetime: 24