spring:
  datasource:
    url: ${GYPSY_BOARD_POSTGRES_URL:jdbc:postgresql://localhost:5435/gypsyboard}
    username: ${GYPSY_BOARD_POSTGRES_USER:admin}
    password: ${GYPSY_BOARD_POSTGRES_PASS:admin}
    driver-class-name: org.postgresql.Driver
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/
  web:
    resources:
      static-locations: classpath:/static
  cache:
    type: "none"

server:
  port: 8000