spring:
  datasource:
    url: ${GYPSY_BOARD_POSTGRES_URL}
    username: ${GYPSY_BOARD_POSTGRES_USER}
    password: ${GYPSY_BOARD_POSTGRES_PASS}
  data:
    mongodb:
      uri: ${GYPSY_BOARD_MONGO_URL}

  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/
  web:
    resources:
      static-locations: classpath:/static
  cache:
    type: "none"
  mail:
    host: ${GYPSY_BOARD_MAIL_HOST}
    port: ${GYPSY_BOARD_MAIL_PORT}
    username: ${GYPSY_BOARD_MAIL_USERNAME}
    password: ${GYPSY_BOARD_MAIL_PASSWORD}
    protocol: ${GYPSY_BOARD_MAIL_PROTOCOL}
    properties.mail.smtp:
      auth: true
      starttls.enable: true

server:
  port: 8000

application.token.lifetime: ${GYPSY_BOARD_TOKEN_LIFETIME} # in hours